repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
        exclude: data/
      - id: check-added-large-files
        args: [--maxkb=1024]
  - repo: local
    hooks:
      - id: ruff-check
        name: "ruff-check"
        language: system
        entry: uvx ruff@0.6.9 check --fix --
        types_or: [python, jupyter]
      - id: typos
        name: typos
        language: system
        entry: uvx typos
        types: [text]
        args: [--write-changes, --force-exclude]
      - id: ruff-format
        name: "ruff-format"
        language: system
        entry: uvx ruff@0.6.9 format --
        types_or: [python, jupyter]
      - id: nbdev-clean
        name: nbdev-clean
        description: "Clean notebooks of metadata that are bad for git diffing"
        types: [jupyter]
        language: system
        entry: ./tools/pre-commit-hooks/nbdev_clean.sh
