name: pre-submit
on:
  pull_request:
  push:
    branches: [main]
jobs:
  pre-commit-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aquaproj/aqua-installer@v3.0.1
        with:
          aqua_version: v2.28.0
      - run: aqua install

      - name: Run tests
        run: ./tools/pre-commit run --all-files
